### ISSUE TITLE
2 bugs found

### ISSUE THREAD

**Issue by JoskeVdB** [cvetaevvitaliy/bq27441#1]
bq27441.c line 311: a "break;" shall be added
bq27441.c line 1064: if (!userConfigControl) BQ27441_enterConfig(**false**); should be: if (!userConfigControl) BQ27441_enterConfig(**true**);

**Comment by cvetaevvitaliy** [comment]
it seems so to you. test it even better )

**Comment by JoskeVdB** [comment]
Anyhow, there is still a bug with userConfigControl
And the break; still needs to be added

**Comment by cvetaevvitaliy** [comment]
> Anyhow, there is still a bug with userConfigControl
> 
> And the break; still needs to be added

then you can add and create PR
